[package]
name = "RegtestSetupForHTLC"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoincore-rpc = "0.19.0"
serde = "1.0"
serde_json = "1.0"
hex = "0.4.3"
anyhow = "1.0.95"
rand = "0.8.4"
bitcoin = "0.32.5"
bitcoin_hashes = "0.14.0"
